[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/ahsan)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4\x9d\0\0\0\x36\0\0\au\0\0\x4-\0\0\x4\x9d\0\0\0\x36\0\0\au\0\0\x4-\0\0\0\0\0\0\0\0\a\x80\0\0\x4\x9d\0\0\0\x36\0\0\au\0\0\x4-)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(490 429)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/ahsan/music/06.%20Imagine%20Dragons%20-%20Rise%20Up.flac, file:///home/ahsan/music/Imagine%20Dragons%20-%20Rise%20Up.mp3, file:///home/ahsan/music/Imagine%20Dragons%20-%20Next%20To%20Me.mp3, file:///home/ahsan/2024-09-19%2023-39-42.mp4, file:///home/ahsan/downloads/video.mp4, file:///home/ahsan/2024-09-04%2021-31-41.mp4, file:///home/ahsan/2024-09-04%2021-28-34.mp4, file:///home/ahsan/Itachi%20Uchiha%20-%20Orignal%20Soundtrack%20%28extended%29%20%5BxYKzdx-B1w0%5D.mp3, file:///home/ahsan/data/onedrive-lums/3d/models/Text%20Animation/renders/test10001-0046.webm, file:///home/ahsan/data/onedrive-lums/3d/models/Text%20Animation/renders/test10001-0046.mp4, file:///home/ahsan/data/onedrive-lums/3d/models/Text%20Animation/renders/test10001-0046.mkv, file:///home/ahsan/data/onedrive-lums/3d/models/Text%20Animation/renders/test10001-0045.mkv, file:///home/ahsan/downloads/Screen%20Recording%202024-07-16%20at%209.24.08%E2%80%AFAM.mov, file:///home/ahsan/downloads/Screen%20Recording%202024-07-16%20at%209.21.52%E2%80%AFAM.mov, file:///home/ahsan/2024-07-15%2018-14-14.mp4, file:///home/ahsan/downloads/sample.mp4, file:///home/ahsan/downloads/Bildschirmaufnahme%202024-05-28%20um%2018.38.03.mp4, file:///home/ahsan/downloads/video%20%285%29.mp4, file:///home/ahsan/downloads/video%20%284%29.mp4, file:///home/ahsan/downloads/video%20%283%29.mp4, file:///home/ahsan/downloads/video%20%282%29.mp4, file:///home/ahsan/downloads/hero-lg-6a98e47708e8.mp4
times=0, 43150, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
